### ISSUE TITLE
Rename to awesome?

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/nice-hosting-providers#2]
https://github.com/sindresorhus/awesome

**Comment by pierreozoux** [comment]
`awesome-FLOSSaaS-Providers` ?

Do you have other ideas?

**Comment by almereyda** [comment]
I'd suppose this could be `awesome-libre-ISPs` or something?

**Comment by pierreozoux** [comment]
I was more on the Hosting Service Providers

But we could be broader and say Internet Service Provider.

Let's stay classic and use: `awesome-hosting-provider`. What do you think?

**Comment by almereyda** [comment]
`awesome-provider-coops`?

**Comment by almereyda** [comment]
@pierreozoux `awesome-hosting`, `awesome-isps` ?

Actually it could read `awesome-indiehosters`, because that's what they are, then the label being a commons.

**Comment by almereyda** [comment]
I have done so for the @ecobytes fork at https://github.com/ecobytes/awesome-indiehosters and unsubscribe from this issue.

**Comment by pierreozoux** [comment]
Sorry, I was a bit out of time lately...

I have troubles to think about IndieHosters.

I see 3 levels:
 - chatons: offering free software as a service with ethic: http://chatons.org/
 - migration network: it is a chatons that agreed to accept migrating users from other chatons
 - IndieHosters is somebody that is using the same infrastructure.

Why not `awesome-librehosting` ?
Actually this is a list of chatons :)
Here is a list (forked a bit from here: https://framagit.org/framasoft/CHATONS/wikis/structures-list)

**Comment by almereyda** [comment]
It is definitely more than hosting what we do. There is, at least for @ecobytes, a lot of training and process controlling involved in our work.

The term `chaton` is completely not understandable for non-french speakers.
At least it seems they forked this list here (look at **in Berlin**), which could be useful for #7.

Yet I agree `libre` is a beautiful prefix. `awesome-librehosters`?

**Comment by pierreozoux** [comment]
Do you provide training to end users of ecobytes?
Do you have a link to such offer (just for my personal reference).

Ok, `awesome-librehosters` it will be :)

(And yes, they forked from here plus added their info)

On 07-06-2016 16:47, jon r wrote:
> It is definitely more than hosting what we do. There is, at least for
> @ecobytes <https://github.com/ecobytes>, a lot of training and process
> controlling involved in our work.
> 
> The term |chaton| is completely not understandable for non-french speakers.
> At least it seems they forked this list here (look at *in Berlin*),
> which could be useful for #7
> <https://github.com/indiehosters/nice-hosting-providers/issues/7>.
> 
> Yet I agree |libre| is a beautiful prefix. |awesome-librehosters|?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/indiehosters/nice-hosting-providers/issues/2#issuecomment-224323551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABxvHWMPWx2npMbPi2uivBsa60i0MZ6Pks5qJZKIgaJpZM4HpTfx>.
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by almereyda** [comment]
I have updated #9 to reflect the choice above by adding https://github.com/indiehosters/nice-hosting-providers/pull/9/commits/b15af9caa5e65a990c94c1c4753d955bbb070585.
