### ISSUE TITLE
Newly found hosting providers are missing

### ISSUE THREAD

**Issue by almereyda** [indiehosters/nice-hosting-providers#5]
I believe they are cool.

http://www.cassiopea.org/

Found them next to Domaine Public on https://annuel.framapad.org/p/Mapping3.0 via https://discourse.transformap.co/t/2016-03-25-bruxelles-mapping-3-0/979

**Comment by pierreozoux** [comment]
Yes please PR :)

**Comment by almereyda** [comment]
Also https://github.com/WebHostingCoopTeam seem to be trustworthy.

**Comment by almereyda** [comment]
Yeah, https://www.tedomum.net/ via @TeDomum via https://github.com/TeDomum/docker-pdns (https://github.com/indiehosters/LibrePaaS/issues/98) via @kaiyou via https://github.com/kaiyou/freeposte.io (similar, but different in comparison with https://github.com/indiehosters/email)

**Comment by almereyda** [comment]
There is also a chance https://www.dyne.org/ doesn't fit in here, but I feel our work should also cover aspects of https://sfconservancy.org/.

**Comment by pierreozoux** [comment]
Just PR and I merge :)
