### ISSUE TITLE
Get hosting for the #nuitdebout" mouvement ?

### ISSUE THREAD

**Issue by SimonSarazin** [indiehosters/nice-hosting-providers#8]
I think the "nuitdebout" mouvement in France need a server. In particular to deploy a wikimedia platform so that all the information is registred / saved somewhere (meeting summery, etc...) and where it's possible to get moderation (For the moment, they all use "pads", but it's difficult to moderate and build collective intelligence on it. Any help ? I can install the mediawiki and the visual editor plugin if needed. We use it for the french commons assembly, and it really help us to deploy the movement (http://assemblee.encommuns.org)

**Comment by pierreozoux** [comment]
Email sent :)

Tell me what you need, and you get it!

On 07-04-2016 10:59, SimonSarazin wrote:
> I think the "nuitdebout" mouvement in France need a server. In
> particular to deploy a wikimedia platform so that all the information is
> registred / saved somewhere (meeting summery, etc...) and where it's
> possible to get moderation (For the moment, they all use "pads", but
> it's difficult to moderate and build collective intelligence on it. Any
> help ? I can install the mediawiki and the visual editor plugin if
> needed. We use it for the french commons assembly, and it really help us
> to deploy the movement (http://assemblee.encommuns.org)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/indiehosters/nice-hosting-providers/issues/8>
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by gandhiano** [comment]
Maybe hackpads, such as in notes.transformap.co? Unfortunately with a few annoying bugs, but I would say possible to overcome in a new, reviewed deployment @almereyda?

**Comment by almereyda** [comment]
The remote issue linked by @SimonSarazin has been closed. Therefore I propose to do the same here, too.
